# Generated by Django 5.2.15 on 2026-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_periode', models.CharField(max_length=20, unique=True)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('nama_periode', models.CharField(max_length=100)),
                ('nama_singkat', models.CharField(max_length=50)),
                ('tanggal_awal_kuliah', models.DateField()),
                ('tanggal_akhir_kuliah', models.DateField()),
                ('tanggal_awal_uts', models.DateField(blank=True, null=True)),
                ('tanggal_akhir_uts', models.DateField(blank=True, null=True)),
                ('tanggal_awal_uas', models.DateField(blank=True, null=True)),
                ('tanggal_akhir_uas', models.DateField(blank=True, null=True)),
                ('total_prodi_terisi', models.IntegerField(default=0)),
                ('status_aktif', models.BooleanField(default=False)),
            ],
        ),
    ]
