# Generated by Django 5.2.15 on 2026-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodeakademik',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
